slam_toolbox:
  ros__parameters:
    use_sim_time: true
    mode: localization
    map_file_name: /home/ros2/ros2_ws/map/labyrinthe_map
    map_start_at_dock: true
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
